config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.i18n import set_language
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from treeflow.views.publications import zotero_view
from strawberry.django.views import AsyncGraphQLView, GraphQLView



urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path("contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"),
    path("publications/",zotero_view, name="publications"),
    path("methodology/", TemplateView.as_view(template_name="pages/methodology.html"), name="methodology"),
    path("resources/", TemplateView.as_view(template_name="pages/resources.html"), name="resources"),
    path("team/", TemplateView.as_view(template_name="pages/team.html"), name="team"),
    path('kosh/', TemplateView.as_view(template_name="index.html"), name="kosh"),
    path('corpus/', include('treeflow.corpus.urls', namespace='corpus')),
    path('dict/', include('treeflow.dict.urls', namespace='dict')),
    path('images/',include('treeflow.images.urls', namespace='images')),
    path("search/", include("treeflow.search.urls", namespace="search")),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("treeflow.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("select2/", include("django_select2.urls")),
    # i18n
    path('i18n/setlang/', set_language, name='set_language'),
    #rest
    path('api/', include('treeflow.rest.urls', namespace='api')),
    # drf-spectacular views
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),




    # Your stuff: custom urls includes go here

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
        #django browser reload
        path("__reload__/", include("django_browser_reload.urls")),

    ]

    if "django_browser_reload" in settings.INSTALLED_APPS:
        urlpatterns = [path("__reload__/", include("django_browser_reload.urls"))] + urlpatterns

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

treeflow/corpus/urls.py
from django.urls import path, re_path
from treeflow.corpus.views.update_token import update_token
from treeflow.corpus.views.update_text import update_text
from treeflow.corpus.views.update_section import update_section_view
from treeflow.corpus.views.update_section_token import update_section_token_view
from treeflow.corpus.views.ud_editor import ud_editor, saveNewDependency, deleteDependency, setNewRoot
from treeflow.corpus.views.tokens import tokens_view
from treeflow.corpus.views.insert_after_token import insert_after_token_view
from treeflow.corpus.views.insert_before_token import insert_before_token_view
from treeflow.corpus.views.delete_token import delete_token_view
from treeflow.corpus.views.delete_section import delete_section_view
from treeflow.corpus.views.texts import texts_view
from treeflow.corpus.views.sections import sections_view
from treeflow.corpus.views.get_sections import get_sections_by_type, get_tokens_for_section, get_section_data
from treeflow.corpus.views.get_images import get_images_view
from treeflow.corpus.views.create_section import create_section_view
from treeflow.corpus.views.section_editor import section_editor_form_view
from treeflow.corpus.views.save_section import save_section_view
from treeflow.corpus.views.display_tokens import display_tokens_view
from treeflow.corpus.views.load_section_modal_create import load_section_modal_create
from treeflow.corpus.views.line_form import line_form_view
from treeflow.corpus.views.get_feature_formset import get_feature_formset
from treeflow.corpus.views.pos_feature_form import pos_feature_form
from treeflow.corpus.views.sentence import sentence_view
from treeflow.corpus.views.sentences import sentences_view
from treeflow.corpus.views.bib_edit import BibEntryCreateView
from treeflow.corpus.views.bibentry import BibEntryListView, BibEntryDetailView
from treeflow.corpus.views.comment_form import comment_form
from treeflow.corpus.views.sources import source_manuscripts , SourceUpdateView, SourceDeleteView, create_source, add_related_source, add_related_bib, sources
from treeflow.corpus.views.dropdown_redirect import dropdown_redirect
from treeflow.corpus.views.update_source import update_source
from treeflow.corpus.views.token_lemma_sense import token_lemma_sense_view
from treeflow.corpus.views.save_token import save_token
from treeflow.corpus.views.manuscripts import manuscripts, get_images_for_manuscript, get_images_for_manuscript_table
from treeflow.corpus.views.export_text import  download_text_mpft, resolve_state_mpft, download_text_conllu, resolve_state_conllu
from treeflow.corpus.views.openseadragon import openseadragon, imageSelector


app_name = "treeflow.corpus"
urlpatterns = [
    path('delete_section/<uuid:section_id>/', delete_section_view, name='delete_section'),
    path('update_section/<uuid:section_id>/', update_section_view, name='update_section'),
    path('update_section_token/<uuid:token_id>/', update_section_token_view, name='update_section_token'),
    path('update_source/<uuid:source_id>/', update_source, name='api_update_source'),
    path('update_text/<uuid:text_id>/', update_text, name='update_text'),
    path('update_token/<uuid:token_id>', update_token, name='update_token'),
    path('ud-editor/<uuid:section_id>/', ud_editor, name='ud_editor'),
    path('ud-editor/saveNewDependency/', saveNewDependency, name='saveDependency'),
    path('ud-editor/deleteDependency/', deleteDependency, name='deleteDependency'),
    path('ud-editor/setNewRoot/', setNewRoot, name='setNewRoot'),
    path('texts/', texts_view, name='texts'),
    path('tokens/<uuid:text_id>', tokens_view, name='tokens'),
    path('tokens/<uuid:text_id>/<uuid:section_id>', tokens_view, name='tokens'),
    path('sentence/<uuid:sentence_id>', sentence_view, name='sentence'),
    path('sentences/<uuid:text_id>', sentences_view, name='sentences'),
    path('sections/<uuid:text_id>', sections_view, name='sections'),
    path('section/', section_editor_form_view, name='section'),
    path('section/<uuid:section_id>', section_editor_form_view, name='section'),
    path('create_section/', create_section_view, name='create_section'),
    path('save_section/', save_section_view, name='save_section'),
    path('save_section/<uuid:section_id>', save_section_view, name='save_section'),
    path('dropdown_redirect/', dropdown_redirect, name='dropdown_redirect'),
    path('get-sections-by-type/', get_sections_by_type, name='get_sections_by_type'),
    path('get-section-data/<uuid:section_id>/', get_section_data, name='get_section_data'),
    path('get-tokens-for-section/<uuid:section_id>/', get_tokens_for_section, name='get_tokens_for_section'),
    path('get-feature-formset/<uuid:token_id>/', get_feature_formset, name='get_feature_formset'),
    path('get-images/', get_images_view, name='get_images'),
    path('display_tokens/', display_tokens_view, name='display_tokens'),
    path('load_section_modal_create/', load_section_modal_create, name='load_section_modal_create'),
    path('line-form/<uuid:token_id>/', line_form_view, name='line_form'),
    path('bibliography/create/', BibEntryCreateView.as_view(), name='bibliography-create'),
    path('pos_feature_form/<uuid:token_id>/', pos_feature_form, name='pos_feature_form'),
    path('bibliography/', BibEntryListView.as_view(), name='bibliography'),
    path('bibliography/<uuid:bibEntry_id>/', BibEntryDetailView.as_view(), name='bibliography-detail'),
    path('bibliography/create/', BibEntryCreateView.as_view(), name='bibliography-create'),
    path('comment_form/<uuid:related_model_id>/', comment_form, name='comment_form'),
    path('sources/',sources, name='sources'),
    path('sources/edit/<uuid:source_id>/', SourceUpdateView.as_view(), name='update_source'),
    path('sources/delete/<uuid:source_id>/', SourceDeleteView.as_view(), name='source_delete'),
    path('sources/add/', create_source, name='source_add'),
    path('sources/add_related_source/<uuid:source_id>/', add_related_source, name='add_related_source'),
    path('sources/add_related_bib/<uuid:source_id>/', add_related_bib, name='add_related_bib'),
    path('sources/manuscripts/', source_manuscripts, name='manuscripts'),
    path('token_lemma_sense/<uuid:token_id>/', token_lemma_sense_view, name='token_lemma_sense'),
    path('save_token/<uuid:token_id>/', save_token, name='save_token'),
    path('manuscripts/', manuscripts, name='manuscripts'),
    path('manuscript/<uuid:manuscript_id>/images',get_images_for_manuscript,name='manuscript_images'),
    path('manuscript/<uuid:manuscript_id>/images/table',get_images_for_manuscript_table,name='manuscript_images_table'),
    path('export/text/mptf/<uuid:text_id>',download_text_mpft,name='mptf'),
    path('export/text/conllu/<uuid:text_id>',download_text_conllu,name='conllu'),
    path('status/text/mptf/<uuid:text_id>',resolve_state_mpft,name='mptf_state'),
    path('status/text/conllu/<uuid:text_id>',resolve_state_conllu,name='conllu_state'),
    path('openseadragon/imageSelect/', imageSelector, name='imageSelector'),
    path('openseadragon/viewer/', openseadragon, name='imageViewer'),
    re_path(r'^tokens/(?P<token_id>[0-9a-f-]+)/insert_after/$', insert_after_token_view, name='insert_after_token'),
    re_path(r'^tokens/(?P<token_id>[0-9a-f-]+)/insert_before/$', insert_before_token_view, name='insert_before_token'),
    re_path(r'^tokens/(?P<token_id>[0-9a-f-]+)/delete/$', delete_token_view, name='delete_token'),
    ]

treeflow/dict/urls.py
from django.urls import include, path
from treeflow.dict.views.save_sense import save_sense
from treeflow.dict.views.save_lemma import save_lemma
from django.views.generic import TemplateView
from treeflow.dict.views.lemma_details import lemma_details

from treeflow.dict.views.lemmas_list import lemmas_list
from treeflow.dict.views.lemma_edit import lemma_edit
from treeflow.dict.views.update_lemma import update_lemma
from treeflow.dict.views.filter_lemmas import filter_lemmas
from treeflow.dict.views.fetch_alphabet import fetch_alphabet
from treeflow.dict.views.dictionary_entry import lemma_details as edit_lemma_details

app_name = "treeflow.dict"
urlpatterns = [
        path("save_sense/", save_sense, name="save_sense"),
        path("save_lemma/", save_lemma, name="save_lemma"),
        path("", lemmas_list, name="dictionary"),
        path("<uuid:lemma_id>/", lemmas_list, name="lemmas"),
        path("fetch_Lemma/<uuid:lemma_id>/",lemma_details, name="lemma_details"),
        path("edit_Lemma/<uuid:lemma_id>/", lemma_edit, name="lemma_edit"),
        path("update_lemma/<uuid:lemma_id>/", update_lemma, name="update_lemma"),
        path("filter_lemmas/", filter_lemmas, name="filter_lemmas"),
        path("fetch_alphabet/", fetch_alphabet, name="fetch_alphabet"),
        path("fetch_attestations/<uuid:lemma_id>/", edit_lemma_details, name="fetch_attestations")
]

treeflow/rest/urls.py
# rest/urls.py
from django.urls import path, include, re_path
from django.conf import settings
from rest_framework.routers import DefaultRouter, SimpleRouter
# import views for corpus
from treeflow.rest.views.bibliography import BibEntryViewSet
from treeflow.rest.views.comment import CommentViewSet
from treeflow.rest.views.dependency import DependencyViewSet
from treeflow.rest.views.feature import FeatureViewSet
from treeflow.rest.views.pos import POSViewSet
from treeflow.rest.views.section import SectionListViewSet, SectionRetrieveViewSet
from treeflow.rest.views.text import TextViewSet
from treeflow.rest.views.token import TokenViewSet
# import views for dictionary
from treeflow.rest.views.lemma import LemmaViewSet
from treeflow.rest.views.sense import SenseViewSet



router = DefaultRouter() if settings.DEBUG else SimpleRouter()

# corpus
router.register(r'bibliography', BibEntryViewSet, basename='bibliography-list')
router.register(r'comments', CommentViewSet, basename='comment-list')
router.register(r'dependencies', DependencyViewSet, basename='dependency-list')
router.register(r'features', FeatureViewSet, basename='feature-list')
router.register(r'pos', POSViewSet, basename='pos-list')
router.register(r'sections', SectionListViewSet, basename='section-list')
router.register(r'sections', SectionRetrieveViewSet, basename='section-detail')
router.register(r'texts', TextViewSet, basename='text-list')
router.register(r'tokens', TokenViewSet, basename='token-list')

# Custom URL pattern for accessing sections by identifier
# dictionary
router.register(r'lemmas', LemmaViewSet, basename='lemmas')
router.register(r'senses', SenseViewSet, basename='sense-list')


app_name = "treeflow.rest"

urlpatterns = [
    path('', include(router.urls)),
]

treeflow/search/urls.py
from django.urls import path

from treeflow.search.render_info_modal import render_info_modal

from . import views

app_name = "treeflow.search"

urlpatterns = [
    path("", views.search_page, name="search"),
    path("results/", views.results_view, name="results"),
    path("info/", render_info_modal, name="info"),
    path("anchors/<uuid:key_value>/", views.get_anchors_from_cache, name="anchors"),
]

treeflow/users/urls.py
from django.urls import path

from treeflow.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

treeflow/corpus/models/bibliography.py
import uuid as uuid_lib
from django.db import models
from django.conf import settings
from django.utils import timezone
from treeflow.utils.normalize import strip_and_normalize

class BibEntry(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid_lib.uuid4, editable=False)
    # Zotero key
    key = models.CharField(blank=True, null=True, max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='created_bib_entries')

    modified_at = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.SET_NULL, 
        null=True, 
        related_name='modified_bib_entries',
        blank=True
    )

    def __str__(self):
        return '{}'.format(self.key)

    def save(self, *args, **kwargs):
        if self.key:  # Ensuring that key is not None before stripping and lowering
            self.key = strip_and_normalize('NFC', self.key)
            self.key = self.key.lower()

        is_new = self._state.adding
        user = kwargs.pop('user', None)  
        # Handle the user for created_by and modified_by
        if is_new and user:
            self.created_by = user
        elif not is_new:
            self.modified_at = timezone.now()
            self.modified_by = user

            # Ensure 'modified_at' and 'modified_by' are included in 'update_fields'
            if 'update_fields' in kwargs:
                update_fields = set(kwargs['update_fields'])
                update_fields.update({'modified_at', 'modified_by'})
                kwargs['update_fields'] = list(update_fields)

        super().save(*args, **kwargs)

treeflow/corpus/models/corpus.py
from django.db import models
import uuid as uuid_lib
from treeflow.utils.normalize import strip_and_normalize

class Corpus(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid_lib.uuid4, editable=False)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)

    
    class Meta:
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'slug'], name='corpus_name_slug'
            )
        ]

    def __str__(self):
        return self.slug
    

    def save(self, *args, **kwargs):
        # Normalize only the `normalized_field` before saving
        self.name = strip_and_normalize('NFC', self.name)
        self.slug = strip_and_normalize('NFC', self.slug)
        super().save(*args, **kwargs)

treeflow/templates/components/footer.html
{% load static tailwind_tags %}

<div class="flex w-full py-3 mt-auto bg-white border-t-4 border-collapse shadow-inner justify-evenly h-fit border-off">
  <div class="h-full m-auto">
    <a href="https://ceres.rub.de/de/" target="_blank"><img src="{% static 'images/logos/ceres.png' %}" alt="Ceres" class="object-scale-down w-3/4 h-16 max-w-sm mx-auto rounded-md shadow-sm cursor-pointer sm:w-3/4 md:w-11/12 lg:w-full opacity-60 hover:opacity-100 hover:shadow-xl" /></a>
  </div>
  <div class="h-full m-auto">
    <a href="https://www.geschkult.fu-berlin.de/e/iranistik/index.html" target="_blank"><img src="{% static 'images/logos/fub.svg' %}" alt="FUB" class="object-scale-down w-3/4 h-16 max-w-sm mx-auto rounded-md shadow-sm cursor-pointer sm:w-3/4 md:w-11/12 lg:w-full opacity-60 hover:opacity-100 hover:shadow-xl" /></a>
  </div>
  <div class="h-full m-auto">
    <a href="https://cceh.uni-koeln.de/" target="_blank"><img src="{% static 'images/logos/cceh-logo.svg' %}" alt="CCeH" class="object-scale-down w-3/4 h-16 max-w-sm mx-auto rounded-md shadow-sm cursor-pointer sm:w-3/4 md:w-11/12 lg:w-full opacity-60 hover:opacity-100 hover:shadow-xl" /></a>
  </div>
  <div class="h-full m-auto">
    <a href="https://gepris.dfg.de/gepris/projekt/452473565?context=projekt&task=showDetail&id=452473565&" target="_blank"><img src="{% static 'images/logos/dfg.png' %}" alt="DFG" class="object-scale-down w-3/4 h-16 max-w-sm mx-auto rounded-md shadow-sm cursor-pointer sm:w-3/4 md:w-11/12 lg:w-full opacity-60 hover:opacity-100 hover:shadow-xl" /></a>
  </div>
</div>

treeflow/templates/components/hero.html
{% load static tailwind_tags %}

<div class="flex flex-col h-64 min-h-[16rem] overflow-hidden">
  <img alt="" src="{% static 'images/container_image.jpg' %}" class="object-contain w-screen" />
</div>

treeflow/templates/components/mobile_scroller.html
{% load static i18n %}
{% load static tailwind_tags %}

<div class="sticky top-0 z-10 bg-white">
  <div class="flex flex-row justify-center w-full gap-1 px-2 text-xs border-b border-gray-400 sm:hidden">
    <a href="{% url 'home' %}">
      <img src="{% static 'images/MPCD-Logo-Final_transparent_ohne-Schriftzug_web.png' %}" class="relative object-contain h-16" alt="MPCD-Logo" />
      <div class="absolute ml-[4.5rem] -mt-4 -rotate-45 text-xs font-semibold text-main-dark [text-shadow:0_2px_4px_rgb(0_0_0_/_40%)]">BETA</div>
    </a>
  </div>
  <div class="sm:hidden flex w-full items-center h-12 min-h-[3rem] bg-white overflow-x-scroll">
    <div class="px-2">
      <a href="{% url 'home' %}" class="p-2 text-center text-main-dark">{% trans 'About' %}</a>
    </div>
    <div class="px-2">
      <a href="{% url 'methodology' %}" class="p-2 text-center text-main-dark">{% trans 'Methodology' %}</a>
    </div>
    <div class="px-2">
      <a href="{% url 'resources' %}" class="p-2 text-center text-main-dark">{% trans 'Resources' %}</a>
    </div>
    <div class="px-2">
      <a href="{% url 'team' %}" class="p-2 text-center text-main-dark">{% trans 'Team' %}</a>
    </div>
    <div class="px-2">
      <a href="{% url 'contact' %}" class="p-2 text-center text-main-dark">{% trans 'Contact' %}</a>
    </div>
  </div>
</div>

treeflow/templates/components/navbar.html
{% load static i18n %}
{% load static tailwind_tags %}

<div class="sticky top-0 z-10 flex flex-row w-full bg-white shadow-md">
  <div class="flex-row items-center justify-between hidden w-full gap-1 px-2 text-xs border-b border-gray-400 sm:flex lg:text-base md:text-sm">
    <a class="cursor-pointer" href="{% url 'home' %}">
      <img src="{% static 'images/MPCD-Logo-Final_transparent_ohne-Schriftzug_web.png' %}" class="relative object-contain h-16" alt="MPCD-Logo" />
      <div class="absolute ml-[4.5rem] -mt-4 -rotate-45 text-xs font-semibold text-main-dark [text-shadow:0_2px_4px_rgb(0_0_0_/_40%)]">BETA</div>
    </a>
    <a href="{% url 'corpus:texts' %}" class="px-2 py-4 text-center cursor-pointer text-main-dark hover:text-off">{% trans 'Texts' %}</a>
    <a href="{% url 'dict:dictionary' %}" class="px-2 py-4 text-center cursor-pointer text-main-dark hover:text-off">{% trans 'Dictionary' %}</a>
    <a href="{% url 'kosh' %}" class="px-2 py-4 text-center cursor-pointer text-main-dark hover:text-off">{% trans 'Glossaries' %}</a>
    <a href="{% url 'search:search' %}" class="px-2 py-4 text-center cursor-pointer text-main-dark hover:text-off">{% trans 'Search' %}</a>
    <a href="{% url 'corpus:manuscripts' %}" class="px-2 py-4 text-center cursor-pointer text-main-dark hover:text-off">{% trans 'Manuscripts' %}</a>
    <a href="{% url 'corpus:sources' %}" class="px-2 py-4 text-center cursor-pointer text-main-dark hover:text-off">{% trans 'Sources' %}</a>
    <a href="{% url 'swagger-ui' %}" class="px-2 py-4 text-center cursor-pointer text-main-dark hover:text-off">{% trans 'API' %}</a>
    <a href="{% url 'publications' %}" class="px-2 py-4 text-center cursor-pointer text-main-dark hover:text-off">{% trans 'Publications' %}</a>
    <a href="{% url 'home' %}" class="px-2 py-4 text-center cursor-pointer text-main-dark hover:text-off">{% trans 'About' %}</a>
    <a href="{% url 'contact' %}" class="px-2 py-4 text-center cursor-pointer text-main-dark hover:text-off">{% trans 'Contact' %}</a>
    
    <div class="inline-block overflow-hidden text-center group">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" class="w-6 h-6 cursor-pointer fill-main-dark hover:fill-off">
        <path fill-rule="evenodd" d="M7 2a1 1 0 011 1v1h3a1 1 0 110 2H9.578a18.87 18.87 0 01-1.724 4.78c.29.354.596.696.914 1.026a1 1 0 11-1.44 1.389c-.188-.196-.373-.396-.554-.6a19.098 19.098 0 01-3.107 3.567 1 1 0 01-1.334-1.49 17.087 17.087 0 003.13-3.733 18.992 18.992 0 01-1.487-2.494 1 1 0 111.79-.89c.234.47.489.928.764 1.372.417-.934.752-1.913.997-2.927H3a1 1 0 110-2h3V3a1 1 0 011-1zm6 6a1 1 0 01.894.553l2.991 5.982a.869.869 0 01.02.037l.99 1.98a1 1 0 11-1.79.895L15.383 16h-4.764l-.724 1.447a1 1 0 11-1.788-.894l.99-1.98.019-.038 2.99-5.982A1 1 0 0113 8zm-1.382 6h2.764L13 11.236 11.618 14z" clip-rule="evenodd"></path>
      </svg>
      <form action="{% url 'set_language' %}" method="post" class="group-hover:flex absolute hidden z-[1] flex-col bg-white border-[1px] rounded-md">
        {% csrf_token %}
        <button type="submit" name="language" value="en" class="p-2 font-bold text-center cursor-pointer font-Helvetica text-main-dark hover:text-off {% if LANGUAGE_CODE == 'en' %}text-off{% endif %}">EN</button>
        <button type="submit" name="language" value="de" class="p-2 font-bold text-center cursor-pointer font-Helvetica text-main-dark hover:text-off {% if LANGUAGE_CODE == 'de' %}text-off{% endif %}">DE</button>
      </form>
    </div>
    <div class="inline-block overflow-hidden text-center group">
      {% if request.user.is_authenticated %}
        <a href="{% url 'account_logout' %}">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" class="w-6 h-6 cursor-pointer fill-main-dark hover:fill-off">
            <path fill-rule="evenodd" d="M3 3a1 1 0 011 1v12a1 1 0 11-2 0V4a1 1 0 011-1zm7.707 3.293a1 1 0 010 1.414L9.414 9H17a1 1 0 110 2H9.414l1.293 1.293a1 1 0 01-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0z" clip-rule="evenodd"></path>
          </svg>
          <div class="group-hover:flex absolute hidden right-3 p-[2px] z-[1] flex-col bg-white border rounded-md">
            <span class="text-center cursor-default text-main-dark">Logout</span>
          </div>
        </a>
      {% else %}
        <a href="{% url 'account_login' %}">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" class="w-6 h-6 cursor-pointer fill-main-dark hover:fill-off">
            <path fill-rule="evenodd" d="M3 3a1 1 0 011 1v12a1 1 0 11-2 0V4a1 1 0 011-1zm7.707 3.293a1 1 0 010 1.414L9.414 9H17a1 1 0 110 2H9.414l1.293 1.293a1 1 0 01-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0z" clip-rule="evenodd"></path>
          </svg>
          <div class="group-hover:flex absolute hidden right-3 p-[2px] z-[1] flex-col bg-white border rounded-md">
            <span class="text-center cursor-default text-main-dark">Login</span>
          </div>
        </a>
      {% endif %}
    </div>
  </div>
</div>