config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.i18n import set_language
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from treeflow.views.publications import zotero_view
from strawberry.django.views import AsyncGraphQLView, GraphQLView



urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path("contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"),
    path("publications/",zotero_view, name="publications"),
    path("methodology/", TemplateView.as_view(template_name="pages/methodology.html"), name="methodology"),
    path("resources/", TemplateView.as_view(template_name="pages/resources.html"), name="resources"),
    path("team/", TemplateView.as_view(template_name="pages/team.html"), name="team"),
    path('kosh/', TemplateView.as_view(template_name="index.html"), name="kosh"),
    path('corpus/', include('treeflow.corpus.urls', namespace='corpus')),
    path('dict/', include('treeflow.dict.urls', namespace='dict')),
    path('images/',include('treeflow.images.urls', namespace='images')),
    path("search/", include("treeflow.search.urls", namespace="search")),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("treeflow.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("select2/", include("django_select2.urls")),
    # i18n
    path('i18n/setlang/', set_language, name='set_language'),
    #rest
    path('api/', include('treeflow.rest.urls', namespace='api')),
    # drf-spectacular views
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),




    # Your stuff: custom urls includes go here

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
        #django browser reload
        path("__reload__/", include("django_browser_reload.urls")),

    ]

    if "django_browser_reload" in settings.INSTALLED_APPS:
        urlpatterns = [path("__reload__/", include("django_browser_reload.urls"))] + urlpatterns

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

treeflow/corpus/urls.py
from django.urls import path, re_path
from treeflow.corpus.views.update_token import update_token
from treeflow.corpus.views.update_text import update_text
from treeflow.corpus.views.update_section import update_section_view
from treeflow.corpus.views.update_section_token import update_section_token_view
from treeflow.corpus.views.ud_editor import ud_editor, saveNewDependency, deleteDependency, setNewRoot
from treeflow.corpus.views.tokens import tokens_view
from treeflow.corpus.views.insert_after_token import insert_after_token_view
from treeflow.corpus.views.insert_before_token import insert_before_token_view
from treeflow.corpus.views.delete_token import delete_token_view
from treeflow.corpus.views.delete_section import delete_section_view
from treeflow.corpus.views.texts import texts_view
from treeflow.corpus.views.sections import sections_view
from treeflow.corpus.views.get_sections import get_sections_by_type, get_tokens_for_section, get_section_data
from treeflow.corpus.views.get_images import get_images_view
from treeflow.corpus.views.create_section import create_section_view
from treeflow.corpus.views.section_editor import section_editor_form_view
from treeflow.corpus.views.save_section import save_section_view
from treeflow.corpus.views.display_tokens import display_tokens_view
from treeflow.corpus.views.load_section_modal_create import load_section_modal_create
from treeflow.corpus.views.line_form import line_form_view
from treeflow.corpus.views.get_feature_formset import get_feature_formset
from treeflow.corpus.views.pos_feature_form import pos_feature_form
from treeflow.corpus.views.sentence import sentence_view
from treeflow.corpus.views.sentences import sentences_view
from treeflow.corpus.views.bib_edit import BibEntryCreateView
from treeflow.corpus.views.bibentry import BibEntryListView, BibEntryDetailView
from treeflow.corpus.views.comment_form import comment_form
from treeflow.corpus.views.sources import source_manuscripts , SourceUpdateView, SourceDeleteView, create_source, add_related_source, add_related_bib, sources
from treeflow.corpus.views.dropdown_redirect import dropdown_redirect
from treeflow.corpus.views.update_source import update_source
from treeflow.corpus.views.token_lemma_sense import token_lemma_sense_view
from treeflow.corpus.views.save_token import save_token
from treeflow.corpus.views.manuscripts import manuscripts, get_images_for_manuscript, get_images_for_manuscript_table
from treeflow.corpus.views.export_text import  download_text_mpft, resolve_state_mpft, download_text_conllu, resolve_state_conllu
from treeflow.corpus.views.openseadragon import openseadragon, imageSelector


app_name = "treeflow.corpus"
urlpatterns = [
    path('delete_section/<uuid:section_id>/', delete_section_view, name='delete_section'),
    path('update_section/<uuid:section_id>/', update_section_view, name='update_section'),
    path('update_section_token/<uuid:token_id>/', update_section_token_view, name='update_section_token'),
    path('update_source/<uuid:source_id>/', update_source, name='api_update_source'),
    path('update_text/<uuid:text_id>/', update_text, name='update_text'),
    path('update_token/<uuid:token_id>', update_token, name='update_token'),
    path('ud-editor/<uuid:section_id>/', ud_editor, name='ud_editor'),
    path('ud-editor/saveNewDependency/', saveNewDependency, name='saveDependency'),
    path('ud-editor/deleteDependency/', deleteDependency, name='deleteDependency'),
    path('ud-editor/setNewRoot/', setNewRoot, name='setNewRoot'),
    path('texts/', texts_view, name='texts'),
    path('tokens/<uuid:text_id>', tokens_view, name='tokens'),
    path('tokens/<uuid:text_id>/<uuid:section_id>', tokens_view, name='tokens'),
    path('sentence/<uuid:sentence_id>', sentence_view, name='sentence'),
    path('sentences/<uuid:text_id>', sentences_view, name='sentences'),
    path('sections/<uuid:text_id>', sections_view, name='sections'),
    path('section/', section_editor_form_view, name='section'),
    path('section/<uuid:section_id>', section_editor_form_view, name='section'),
    path('create_section/', create_section_view, name='create_section'),
    path('save_section/', save_section_view, name='save_section'),
    path('save_section/<uuid:section_id>', save_section_view, name='save_section'),
    path('dropdown_redirect/', dropdown_redirect, name='dropdown_redirect'),
    path('get-sections-by-type/', get_sections_by_type, name='get_sections_by_type'),
    path('get-section-data/<uuid:section_id>/', get_section_data, name='get_section_data'),
    path('get-tokens-for-section/<uuid:section_id>/', get_tokens_for_section, name='get_tokens_for_section'),
    path('get-feature-formset/<uuid:token_id>/', get_feature_formset, name='get_feature_formset'),
    path('get-images/', get_images_view, name='get_images'),
    path('display_tokens/', display_tokens_view, name='display_tokens'),
    path('load_section_modal_create/', load_section_modal_create, name='load_section_modal_create'),
    path('line-form/<uuid:token_id>/', line_form_view, name='line_form'),
    path('bibliography/create/', BibEntryCreateView.as_view(), name='bibliography-create'),
    path('pos_feature_form/<uuid:token_id>/', pos_feature_form, name='pos_feature_form'),
    path('bibliography/', BibEntryListView.as_view(), name='bibliography'),
    path('bibliography/<uuid:bibEntry_id>/', BibEntryDetailView.as_view(), name='bibliography-detail'),
    path('bibliography/create/', BibEntryCreateView.as_view(), name='bibliography-create'),
    path('comment_form/<uuid:related_model_id>/', comment_form, name='comment_form'),
    path('sources/',sources, name='sources'),
    path('sources/edit/<uuid:source_id>/', SourceUpdateView.as_view(), name='update_source'),
    path('sources/delete/<uuid:source_id>/', SourceDeleteView.as_view(), name='source_delete'),
    path('sources/add/', create_source, name='source_add'),
    path('sources/add_related_source/<uuid:source_id>/', add_related_source, name='add_related_source'),
    path('sources/add_related_bib/<uuid:source_id>/', add_related_bib, name='add_related_bib'),
    path('sources/manuscripts/', source_manuscripts, name='manuscripts'),
    path('token_lemma_sense/<uuid:token_id>/', token_lemma_sense_view, name='token_lemma_sense'),
    path('save_token/<uuid:token_id>/', save_token, name='save_token'),
    path('manuscripts/', manuscripts, name='manuscripts'),
    path('manuscript/<uuid:manuscript_id>/images',get_images_for_manuscript,name='manuscript_images'),
    path('manuscript/<uuid:manuscript_id>/images/table',get_images_for_manuscript_table,name='manuscript_images_table'),
    path('export/text/mptf/<uuid:text_id>',download_text_mpft,name='mptf'),
    path('export/text/conllu/<uuid:text_id>',download_text_conllu,name='conllu'),
    path('status/text/mptf/<uuid:text_id>',resolve_state_mpft,name='mptf_state'),
    path('status/text/conllu/<uuid:text_id>',resolve_state_conllu,name='conllu_state'),
    path('openseadragon/imageSelect/', imageSelector, name='imageSelector'),
    path('openseadragon/viewer/', openseadragon, name='imageViewer'),
    re_path(r'^tokens/(?P<token_id>[0-9a-f-]+)/insert_after/$', insert_after_token_view, name='insert_after_token'),
    re_path(r'^tokens/(?P<token_id>[0-9a-f-]+)/insert_before/$', insert_before_token_view, name='insert_before_token'),
    re_path(r'^tokens/(?P<token_id>[0-9a-f-]+)/delete/$', delete_token_view, name='delete_token'),
    ]

treeflow/dict/urls.py
from django.urls import include, path
from treeflow.dict.views.save_sense import save_sense
from treeflow.dict.views.save_lemma import save_lemma
from django.views.generic import TemplateView
from treeflow.dict.views.lemma_details import lemma_details

from treeflow.dict.views.lemmas_list import lemmas_list
from treeflow.dict.views.lemma_edit import lemma_edit
from treeflow.dict.views.update_lemma import update_lemma
from treeflow.dict.views.filter_lemmas import filter_lemmas
from treeflow.dict.views.fetch_alphabet import fetch_alphabet
from treeflow.dict.views.dictionary_entry import lemma_details as edit_lemma_details

app_name = "treeflow.dict"
urlpatterns = [
        path("save_sense/", save_sense, name="save_sense"),
        path("save_lemma/", save_lemma, name="save_lemma"),
        path("", lemmas_list, name="dictionary"),
        path("<uuid:lemma_id>/", lemmas_list, name="lemmas"),
        path("fetch_Lemma/<uuid:lemma_id>/",lemma_details, name="lemma_details"),
        path("edit_Lemma/<uuid:lemma_id>/", lemma_edit, name="lemma_edit"),
        path("update_lemma/<uuid:lemma_id>/", update_lemma, name="update_lemma"),
        path("filter_lemmas/", filter_lemmas, name="filter_lemmas"),
        path("fetch_alphabet/", fetch_alphabet, name="fetch_alphabet"),
        path("fetch_attestations/<uuid:lemma_id>/", edit_lemma_details, name="fetch_attestations")
]

treeflow/rest/urls.py
# rest/urls.py
from django.urls import path, include, re_path
from django.conf import settings
from rest_framework.routers import DefaultRouter, SimpleRouter
# import views for corpus
from treeflow.rest.views.bibliography import BibEntryViewSet
from treeflow.rest.views.comment import CommentViewSet
from treeflow.rest.views.dependency import DependencyViewSet
from treeflow.rest.views.feature import FeatureViewSet
from treeflow.rest.views.pos import POSViewSet
from treeflow.rest.views.section import SectionListViewSet, SectionRetrieveViewSet
from treeflow.rest.views.text import TextViewSet
from treeflow.rest.views.token import TokenViewSet
# import views for dictionary
from treeflow.rest.views.lemma import LemmaViewSet
from treeflow.rest.views.sense import SenseViewSet



router = DefaultRouter() if settings.DEBUG else SimpleRouter()

# corpus
router.register(r'bibliography', BibEntryViewSet, basename='bibliography-list')
router.register(r'comments', CommentViewSet, basename='comment-list')
router.register(r'dependencies', DependencyViewSet, basename='dependency-list')
router.register(r'features', FeatureViewSet, basename='feature-list')
router.register(r'pos', POSViewSet, basename='pos-list')
router.register(r'sections', SectionListViewSet, basename='section-list')
router.register(r'sections', SectionRetrieveViewSet, basename='section-detail')
router.register(r'texts', TextViewSet, basename='text-list')
router.register(r'tokens', TokenViewSet, basename='token-list')

# Custom URL pattern for accessing sections by identifier
# dictionary
router.register(r'lemmas', LemmaViewSet, basename='lemmas')
router.register(r'senses', SenseViewSet, basename='sense-list')


app_name = "treeflow.rest"

urlpatterns = [
    path('', include(router.urls)),
]

treeflow/search/urls.py
from django.urls import path

from treeflow.search.render_info_modal import render_info_modal

from . import views

app_name = "treeflow.search"

urlpatterns = [
    path("", views.search_page, name="search"),
    path("results/", views.results_view, name="results"),
    path("info/", render_info_modal, name="info"),
    path("anchors/<uuid:key_value>/", views.get_anchors_from_cache, name="anchors"),
]

treeflow/users/urls.py
from django.urls import path

from treeflow.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

treeflow/corpus/models/bibliography.py
import uuid as uuid_lib
from django.db import models
from django.conf import settings
from django.utils import timezone
from treeflow.utils.normalize import strip_and_normalize

class BibEntry(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid_lib.uuid4, editable=False)
    # Zotero key
    key = models.CharField(blank=True, null=True, max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='created_bib_entries')

    modified_at = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.SET_NULL, 
        null=True, 
        related_name='modified_bib_entries',
        blank=True
    )

    def __str__(self):
        return '{}'.format(self.key)

    def save(self, *args, **kwargs):
        if self.key:  # Ensuring that key is not None before stripping and lowering
            self.key = strip_and_normalize('NFC', self.key)
            self.key = self.key.lower()

        is_new = self._state.adding
        user = kwargs.pop('user', None)  
        # Handle the user for created_by and modified_by
        if is_new and user:
            self.created_by = user
        elif not is_new:
            self.modified_at = timezone.now()
            self.modified_by = user

            # Ensure 'modified_at' and 'modified_by' are included in 'update_fields'
            if 'update_fields' in kwargs:
                update_fields = set(kwargs['update_fields'])
                update_fields.update({'modified_at', 'modified_by'})
                kwargs['update_fields'] = list(update_fields)

        super().save(*args, **kwargs)

treeflow/corpus/models/corpus.py
from django.db import models
import uuid as uuid_lib
from treeflow.utils.normalize import strip_and_normalize

class Corpus(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid_lib.uuid4, editable=False)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)

    
    class Meta:
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'slug'], name='corpus_name_slug'
            )
        ]

    def __str__(self):
        return self.slug
    

    def save(self, *args, **kwargs):
        # Normalize only the `normalized_field` before saving
        self.name = strip_and_normalize('NFC', self.name)
        self.slug = strip_and_normalize('NFC', self.slug)
        super().save(*args, **kwargs)

treeflow/templates/search/_partial.html
{% load static i18n %}
{% block extra_head %}

{% if key %}
<script>
  function fetchHighlighting(){
    key = "{{key}}";

    fetch('{% url "search:anchors" key_value=key %}').then(response => response.json()).then(data => {

      document.querySelectorAll('span.token-span').forEach(span => {
        span.classList.remove('font-bold', 'text-off', 'bg-main', 'text-white', 'text-red-500');
        const id = span.getAttribute('id');
        if (data.anchors.includes(id)) {
          span.classList.add('font-bold', 'text-off');
        } 
        if (data.hits && data.hits.includes(id)) {
          span.classList.add('bg-main', 'font-bold', 'text-white');
        } 
        if (span.textContent == "None") {
          span.classList.add('text-red-500');
        }
      });
    }).catch(error => {
      console.error(error);
    });
  }
  
  document.addEventListener('htmx:afterSwap', () => { fetchHighlighting(); });
  fetchHighlighting();
</script>
{% endif %}

{% endblock %}

<div id="search-page-container" class="flex flex-col gap-4 p-4">
    <div id="search" class="flex flex-col border shadow shadow-black/10">
        <div class="flex items-center justify-center w-full h-12 font-semibold shadow shadow-black/10">
            <h3>Search</h3>
        </div>
        <div id="search-type" class="flex flex-row items-center gap-4 m-4">
            <select id="search-type-selection" class="rounded" name="layout_selection" hx-get="{% url 'search:search' %}" hx-target="#search-page-container" hx-swap="outerHTML">
                <option value="logical-section" {% if layout_selection == "logical-section" %}selected{% endif %}>Section - Logical operators</option>
                <option value="logical-token" {% if layout_selection == "logical-token" %}selected{% endif %}>Token - Logical operators</option>
                <option value="distance-section" {% if layout_selection == "distance-section" %}selected{% endif %}>Token distance</option>
            </select>
            <label class="font-bold text-gray-900 whitespace-nowrap">
                Search tokens
                {% if "distance" in layout_selection %}by looking for entries with a specific distance between them{% endif %}
                {% if "logical" in layout_selection %}by combining queries using logical operators{% endif %}
            </label>
        </div>
        <div id="search-forms" class="overflow-x-auto text-center">
            {% include "search/formset.html" %}
        </div>
    </div>
    <div id="results-div" class="flex-col hidden border shadow shadow-black/10">
        <div class="flex items-center justify-center w-full h-12 font-semibold shadow shadow-black/10">
            <h3>Results</h3>
        </div>
        <div id="loadingIndicator" class="flex-row justify-center hidden">
            <img class="w-20 h-20 m-6" src="{% static 'search/three-dots.svg' %}" />
        </div>
        <div id="results-list" class="flex flex-col">
        </div>
    </div>
</div>

<div id="section-info-modal" class="fixed inset-0 z-10 hidden overflow-y-auto bg-gray-500 bg-opacity-50"></div>

<script>
  const addForm = (buttonElement) => {
    const currentForm = buttonElement.parentElement.parentElement.id;
    const formsCountElement = document.getElementById('id_form-TOTAL_FORMS');
    const formsCount = parseInt(formsCountElement.value);
    const emptyFormHtml = document.getElementById('empty-form').innerHTML;
    const uniqueId = Date.now() + Math.random().toString(36).substring(2, 11);

    let newFormHtml = emptyFormHtml
      .replace(/__prefix__/g, formsCount)
      .replace('<div', `<div id="form-${uniqueId}"`);

    document.getElementById(currentForm).insertAdjacentHTML('afterend', newFormHtml);
    formsCountElement.value = formsCount + 1;
  }

  const removeForm = (buttonElement) => {
    const formToRemove = buttonElement.parentElement.parentElement;
    const formsCountElement = document.getElementById('id_form-TOTAL_FORMS');
    const formsCount = parseInt(formsCountElement.value);

    if (formsCount > 1) {
      formToRemove.remove();
      formsCountElement.value = formsCount - 1;
    }
  }

  const activateLoadingSVG = () => {
    document.getElementById('results-list').innerHTML = '';

    const resultsDiv = document.getElementById('results-div');
    if (resultsDiv.classList.contains('hidden')) {
      resultsDiv.classList.remove('hidden');
      resultsDiv.classList.add('flex');
    }

    const loadingIndicator = document.getElementById('loadingIndicator');
    if (loadingIndicator.classList.contains('hidden')) {
      loadingIndicator.classList.remove('hidden');
      loadingIndicator.classList.add('flex');
    }
  }

  const deactivateLoadingSVG = () => {
    const loadingIndicator = document.getElementById('loadingIndicator');
    if (loadingIndicator.classList.contains('flex')) {
      loadingIndicator.classList.remove('flex');
      loadingIndicator.classList.add('hidden');
    }
  }

  document.body.addEventListener('htmx:afterSwap', function () {
    deactivateLoadingSVG();
  });
</script>

treeflow/templates/search/formset.html
<form id="form-set" hx-get="{% url "search:results" %}" hx-target="#results-list" hx-indicator="#loadingIndicator" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <input type="hidden" name="layout_selection" value="{{ layout_selection }}" class="rounded">
    {% if formset.non_form_errors %}
        <div id="formset-errors">
            {% for error in formset.non_form_errors %}
                <div class="text-red-500">{{ error }}</div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="flex flex-row flex-wrap justify-center w-full gap-8 py-4">
        {{ formset.management_form }}
        <div id="empty-form" style="display:none">
            <div class="relative flex flex-col p-8 bg-white border rounded-lg shadow w-min shadow-black/10">
                {% include 'search/form.html' with form=formset.empty_form firstForm=False layout=layout_selection %}
            </div>
        </div>
        {% for form in formset %}
            <div id="form-initial" class="relative flex flex-col p-8 bg-white border rounded-lg shadow w-min shadow-black/10">
                {% include 'search/form.html' with form=form firstForm=forloop.first layout=layout_selection %}
            </div>
        {% endfor %}
    </div>
</form>
<input form="form-set" type="submit" value="Search" onclick="activateLoadingSVG()"
        class="w-[10%] p-2 rounded bg-main text-white hover:bg-main-dark cursor-pointer mt-2 mb-4 text-center transition-colors duration-150" />

treeflow/templates/search/loading_bite.html
{% load tailwind_tags %}

<div class="flex justify-center w-full overflow-hidden gap-x-1">
  <div class="w-1 h-4 ease-in-out rounded-md bg-off animate-infinite animate-fade-up animate-delay-0"></div>
  <div class="w-1 h-5 rounded-md bg-off animate-infinite animate-fade-up animate-delay-75"></div>
  <div class="w-1 h-6 rounded-md bg-off animate-infinite animate-fade-up animate-delay-150"></div>
  <div class="w-1 h-5 rounded-md bg-off animate-infinite animate-fade-up animate-delay-[225ms]"></div>
  <div class="w-1 h-4 rounded-md bg-off animate-infinite animate-fade-up animate-delay-300"></div>
</div>

treeflow/templates/search/section-links.html
<div class="flex flex-row gap-1">
  <div id="ud-link" title="Open Universal Dependency Graph" class="rounded-md cursor-pointer group">
    <a href="{% url 'corpus:ud_editor' section.id %}" class="flex align-middle" target="_blank">
      <svg class="w-6 h-6 -rotate-90 text-main group-hover:text-action" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z" /> <circle cx="7" cy="18" r="2" /> <circle cx="7" cy="6" r="2" /> <circle cx="17" cy="12" r="2" /> <line x1="7" y1="8" x2="7" y2="16" /> <path d="M7 8a4 4 0 0 0 4 4h4" />
      </svg>
    </a>
  </div>

  <div id="section-link" title="Open section viewer" class="rounded-md cursor-pointer group">
    <a href="{% url 'corpus:sections' text_id=section.text.id %}#{{ section.id }}" class="flex align-middle" target="_blank">
      <svg class="w-6 h-6 text-main group-hover:text-action" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <rect x="3" y="3" width="18" height="18" rx="2" ry="2" /> <line x1="3" y1="9" x2="21" y2="9" /> <line x1="9" y1="21" x2="9" y2="9" />
      </svg>
    </a>
  </div>

  {% if request.user.is_authenticated %}
    <div id="edit-link" title="Edit this section" class="rounded-md cursor-pointer group">
      <a href="{% url 'corpus:sentence' section.id %}?text_id={{ section.text.id }}" class="flex align-middle" target="_blank">
        <svg class="w-6 h-6 text-main group-hover:text-action" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" /> <path d="M9 7 h-3a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-3" /> <path d="M9 15h3l8.5 -8.5a1.5 1.5 0 0 0 -3 -3l-8.5 8.5v3" /> <line x1="16" y1="5" x2="19" y2="8" />
        </svg>
      </a>
    </div>
  {% endif %}

  <div id="info-modal-link" title="Open section information" class="rounded-md cursor-pointer group" hx-get="{% url 'search:info' %}?section_id={{ section.id }}" hx-trigger="click" hx-target="#section-info-modal" onclick="showSectionInfoModal()">
    <svg class="w-6 h-6 text-main group-hover:text-action" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  </div>
</div>

<script>
  function showSectionInfoModal(){
    document.getElementById("section-info-modal").classList.remove("hidden");
  }
</script>