config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.i18n import set_language
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from treeflow.views.publications import zotero_view
from strawberry.django.views import AsyncGraphQLView, GraphQLView



urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path("contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"),
    path("publications/",zotero_view, name="publications"),
    path("methodology/", TemplateView.as_view(template_name="pages/methodology.html"), name="methodology"),
    path("resources/", TemplateView.as_view(template_name="pages/resources.html"), name="resources"),
    path("team/", TemplateView.as_view(template_name="pages/team.html"), name="team"),
    path('kosh/', TemplateView.as_view(template_name="index.html"), name="kosh"),
    path('corpus/', include('treeflow.corpus.urls', namespace='corpus')),
    path('dict/', include('treeflow.dict.urls', namespace='dict')),
    path('images/',include('treeflow.images.urls', namespace='images')),
    path("search/", include("treeflow.search.urls", namespace="search")),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("treeflow.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("select2/", include("django_select2.urls")),
    # i18n
    path('i18n/setlang/', set_language, name='set_language'),
    #rest
    path('api/', include('treeflow.rest.urls', namespace='api')),
    # drf-spectacular views
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),




    # Your stuff: custom urls includes go here

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
        #django browser reload
        path("__reload__/", include("django_browser_reload.urls")),

    ]

    if "django_browser_reload" in settings.INSTALLED_APPS:
        urlpatterns = [path("__reload__/", include("django_browser_reload.urls"))] + urlpatterns

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

treeflow/corpus/urls.py
from django.urls import path, re_path
from treeflow.corpus.views.update_token import update_token
from treeflow.corpus.views.update_text import update_text
from treeflow.corpus.views.update_section import update_section_view
from treeflow.corpus.views.update_section_token import update_section_token_view
from treeflow.corpus.views.ud_editor import ud_editor, saveNewDependency, deleteDependency, setNewRoot
from treeflow.corpus.views.tokens import tokens_view
from treeflow.corpus.views.insert_after_token import insert_after_token_view
from treeflow.corpus.views.insert_before_token import insert_before_token_view
from treeflow.corpus.views.delete_token import delete_token_view
from treeflow.corpus.views.delete_section import delete_section_view
from treeflow.corpus.views.texts import texts_view
from treeflow.corpus.views.sections import sections_view
from treeflow.corpus.views.get_sections import get_sections_by_type, get_tokens_for_section, get_section_data
from treeflow.corpus.views.get_images import get_images_view
from treeflow.corpus.views.create_section import create_section_view
from treeflow.corpus.views.section_editor import section_editor_form_view
from treeflow.corpus.views.save_section import save_section_view
from treeflow.corpus.views.display_tokens import display_tokens_view
from treeflow.corpus.views.load_section_modal_create import load_section_modal_create
from treeflow.corpus.views.line_form import line_form_view
from treeflow.corpus.views.get_feature_formset import get_feature_formset
from treeflow.corpus.views.pos_feature_form import pos_feature_form
from treeflow.corpus.views.sentence import sentence_view
from treeflow.corpus.views.sentences import sentences_view
from treeflow.corpus.views.bib_edit import BibEntryCreateView
from treeflow.corpus.views.bibentry import BibEntryListView, BibEntryDetailView
from treeflow.corpus.views.comment_form import comment_form
from treeflow.corpus.views.sources import source_manuscripts , SourceUpdateView, SourceDeleteView, create_source, add_related_source, add_related_bib, sources
from treeflow.corpus.views.dropdown_redirect import dropdown_redirect
from treeflow.corpus.views.update_source import update_source
from treeflow.corpus.views.token_lemma_sense import token_lemma_sense_view
from treeflow.corpus.views.save_token import save_token
from treeflow.corpus.views.manuscripts import manuscripts, get_images_for_manuscript, get_images_for_manuscript_table
from treeflow.corpus.views.export_text import  download_text_mpft, resolve_state_mpft, download_text_conllu, resolve_state_conllu
from treeflow.corpus.views.openseadragon import openseadragon, imageSelector


app_name = "treeflow.corpus"
urlpatterns = [
    path('delete_section/<uuid:section_id>/', delete_section_view, name='delete_section'),
    path('update_section/<uuid:section_id>/', update_section_view, name='update_section'),
    path('update_section_token/<uuid:token_id>/', update_section_token_view, name='update_section_token'),
    path('update_source/<uuid:source_id>/', update_source, name='api_update_source'),
    path('update_text/<uuid:text_id>/', update_text, name='update_text'),
    path('update_token/<uuid:token_id>', update_token, name='update_token'),
    path('ud-editor/<uuid:section_id>/', ud_editor, name='ud_editor'),
    path('ud-editor/saveNewDependency/', saveNewDependency, name='saveDependency'),
    path('ud-editor/deleteDependency/', deleteDependency, name='deleteDependency'),
    path('ud-editor/setNewRoot/', setNewRoot, name='setNewRoot'),
    path('texts/', texts_view, name='texts'),
    path('tokens/<uuid:text_id>', tokens_view, name='tokens'),
    path('tokens/<uuid:text_id>/<uuid:section_id>', tokens_view, name='tokens'),
    path('sentence/<uuid:sentence_id>', sentence_view, name='sentence'),
    path('sentences/<uuid:text_id>', sentences_view, name='sentences'),
    path('sections/<uuid:text_id>', sections_view, name='sections'),
    path('section/', section_editor_form_view, name='section'),
    path('section/<uuid:section_id>', section_editor_form_view, name='section'),
    path('create_section/', create_section_view, name='create_section'),
    path('save_section/', save_section_view, name='save_section'),
    path('save_section/<uuid:section_id>', save_section_view, name='save_section'),
    path('dropdown_redirect/', dropdown_redirect, name='dropdown_redirect'),
    path('get-sections-by-type/', get_sections_by_type, name='get_sections_by_type'),
    path('get-section-data/<uuid:section_id>/', get_section_data, name='get_section_data'),
    path('get-tokens-for-section/<uuid:section_id>/', get_tokens_for_section, name='get_tokens_for_section'),
    path('get-feature-formset/<uuid:token_id>/', get_feature_formset, name='get_feature_formset'),
    path('get-images/', get_images_view, name='get_images'),
    path('display_tokens/', display_tokens_view, name='display_tokens'),
    path('load_section_modal_create/', load_section_modal_create, name='load_section_modal_create'),
    path('line-form/<uuid:token_id>/', line_form_view, name='line_form'),
    path('bibliography/create/', BibEntryCreateView.as_view(), name='bibliography-create'),
    path('pos_feature_form/<uuid:token_id>/', pos_feature_form, name='pos_feature_form'),
    path('bibliography/', BibEntryListView.as_view(), name='bibliography'),
    path('bibliography/<uuid:bibEntry_id>/', BibEntryDetailView.as_view(), name='bibliography-detail'),
    path('bibliography/create/', BibEntryCreateView.as_view(), name='bibliography-create'),
    path('comment_form/<uuid:related_model_id>/', comment_form, name='comment_form'),
    path('sources/',sources, name='sources'),
    path('sources/edit/<uuid:source_id>/', SourceUpdateView.as_view(), name='update_source'),
    path('sources/delete/<uuid:source_id>/', SourceDeleteView.as_view(), name='source_delete'),
    path('sources/add/', create_source, name='source_add'),
    path('sources/add_related_source/<uuid:source_id>/', add_related_source, name='add_related_source'),
    path('sources/add_related_bib/<uuid:source_id>/', add_related_bib, name='add_related_bib'),
    path('sources/manuscripts/', source_manuscripts, name='manuscripts'),
    path('token_lemma_sense/<uuid:token_id>/', token_lemma_sense_view, name='token_lemma_sense'),
    path('save_token/<uuid:token_id>/', save_token, name='save_token'),
    path('manuscripts/', manuscripts, name='manuscripts'),
    path('manuscript/<uuid:manuscript_id>/images',get_images_for_manuscript,name='manuscript_images'),
    path('manuscript/<uuid:manuscript_id>/images/table',get_images_for_manuscript_table,name='manuscript_images_table'),
    path('export/text/mptf/<uuid:text_id>',download_text_mpft,name='mptf'),
    path('export/text/conllu/<uuid:text_id>',download_text_conllu,name='conllu'),
    path('status/text/mptf/<uuid:text_id>',resolve_state_mpft,name='mptf_state'),
    path('status/text/conllu/<uuid:text_id>',resolve_state_conllu,name='conllu_state'),
    path('openseadragon/imageSelect/', imageSelector, name='imageSelector'),
    path('openseadragon/viewer/', openseadragon, name='imageViewer'),
    re_path(r'^tokens/(?P<token_id>[0-9a-f-]+)/insert_after/$', insert_after_token_view, name='insert_after_token'),
    re_path(r'^tokens/(?P<token_id>[0-9a-f-]+)/insert_before/$', insert_before_token_view, name='insert_before_token'),
    re_path(r'^tokens/(?P<token_id>[0-9a-f-]+)/delete/$', delete_token_view, name='delete_token'),
    ]

treeflow/corpus/forms/bibentry_forms.py
from django import forms
from treeflow.corpus.models import BibEntry

class BibEntryForm(forms.ModelForm):
    class Meta:
        fields = '__all__'
        model = BibEntry

treeflow/corpus/forms/comment_form.py
from django import forms
from django.forms import modelformset_factory
from treeflow.corpus.models.comment import Comment
from django.core.validators import RegexValidator


class SingleCharField(forms.CharField):
    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 1
        kwargs['validators'] = [RegexValidator(
            r'^[A-Z]$', 'Only uppercase characters are allowed')]
        super(SingleCharField, self).__init__(*args, **kwargs)


class CommentForm(forms.ModelForm):
    related_model_id = forms.CharField(
        widget=forms.HiddenInput(), required=False, initial=None)
    related_model_type = forms.CharField(
        widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Comment
        fields = ['comment', 'related_model_id', 'related_model_type',
                  'uncertain', 'to_discuss', 'new_suggestion']

    def __init__(self, *args, **kwargs):
        related_model_type = kwargs.pop('related_model_type', None)
        related_model_id = kwargs.pop('related_model_id', None)
        super().__init__(*args, **kwargs)

        self.fields['related_model_type'].initial = related_model_type
        self.fields['related_model_id'].initial = related_model_id

        if related_model_type == 'Token':
            self.fields['uncertain'] = SingleCharField(
                widget=forms.TextInput(), required=False)
            self.fields['to_discuss'] = SingleCharField(
                widget=forms.TextInput(), required=False)
            self.fields['new_suggestion'] = SingleCharField(
                widget=forms.TextInput(), required=False)

        def clean_uncertain(self):
            data = self.cleaned_data.get('uncertain', '')
            if isinstance(data, str):
                return list(filter(None, data.upper().split(',')))
            return data  # Already a list or another type, return as is

        def clean_to_discuss(self):
            data = self.cleaned_data.get('to_discuss', '')
            if isinstance(data, str):
                return list(filter(None, data.upper().split(',')))
            return data

        def clean_new_suggestion(self):
            data = self.cleaned_data.get('new_suggestion', '')
            if isinstance(data, str):
                return list(filter(None, data.upper().split(',')))
            return data


# Usage of formset in your view
CommentFormSet = modelformset_factory(
    Comment, form=CommentForm, extra=1, can_delete=True)

treeflow/corpus/forms/comment_section_form.py
from django import forms
from treeflow.corpus.models.comment import Comment

class CommentSectionForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment', 'user']  # Include user to handle it in the form, but it will be set automatically

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)  # Extract user from kwargs and remove it
        super(CommentSectionForm, self).__init__(*args, **kwargs)
        self.fields['user'].required = False
        self.fields['user'].widget = forms.HiddenInput()  # Hide the user field
        self.fields['comment'].widget = forms.Textarea(attrs={'rows': 3, 'placeholder': 'Enter your comment here...'})

    def save(self, commit=True):
        instance = super(CommentSectionForm, self).save(commit=False)
        if not instance.user_id:  # Set user only if it's not already set
            instance.user = self.user
        if commit:
            instance.save()
        return instance

treeflow/corpus/forms/feature_forms.py
from django import forms
from django.forms import inlineformset_factory
from treeflow.corpus.models import Token, Feature

class FeatureForm(forms.ModelForm):

    class Meta:
        exclude = ('pos',)  # Exclude the 'pos' field from the feature form
        fields = ['feature', 'feature_value']

# Create an inline formset factory
FeatureFormSet = inlineformset_factory(Token, Feature, form=FeatureForm, extra=4,can_delete=True)

treeflow/corpus/forms/line_form.py
from django import forms
from treeflow.corpus.models import Section, Text
import logging

logger = logging.getLogger(__name__)

class AssignLineSectionForm(forms.ModelForm):
    
    identifier = forms.ModelChoiceField(queryset=Section.objects.none(), label="Section", required=False)

    class Meta:
        model = Section
        fields = ['identifier']

    def __init__(self, *args, **kwargs):
        self.text_id = kwargs.pop('text_id', None)
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if self.text_id:
            try:
                text = Text.objects.get(id=self.text_id)
                section_queryset = Section.objects.filter(text=text, type="line")
                self.fields['identifier'].queryset = section_queryset

            except Text.DoesNotExist:
                logger.debug("Text with id %s does not exist", self.text_id) 
        else:
            logger.debug("No text_id provided")        


class CreateLineSectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = ["identifier", 'title', 'number']

treeflow/corpus/forms/pos_form.py
from django import forms
from django.forms import inlineformset_factory
from treeflow.corpus.models import POS, Token

class POSForm(forms.ModelForm):
    class Meta:
        model = POS
        fields = ('pos', 'type')
        widgets = {
            'type': forms.HiddenInput(),  # Makes the type field hidden
        }

    def __init__(self, *args, **kwargs):
        super(POSForm, self).__init__(*args, **kwargs)
        self.fields['type'].initial = 'upos'  # Sets a default value for type

# POSFormSet to manage a collection of POS forms
POSFormSet = inlineformset_factory(
    Token, POS, form=POSForm,
    fields=('pos', 'type'),  # Specify the fields here, the type will be included but hidden
        can_delete=True,  # No delete checkbox
    extra=1,  # No extra forms
)

treeflow/corpus/templates/bibentry_create.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'Create Bib Entry' %}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans 'Create' %}</button>
    </form>
{% endblock %}

treeflow/corpus/templates/bibentry_detail.html
<!-- bibentry_detail.html -->

{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="container flex flex-col gap-10 p-2 mx-auto">
  <h2>{{ zotero_entry.data.title|safe }}</h2>
  <div class="p-2 -mt-10">

    <p><strong>Author:</strong>
      {%for author in zotero_entry.data.creators%}
      {{ author.firstName }} {{ author.lastName }}
      {%if not forloop.last%}
      ,
      {%endif%}
      {%endfor%}
    </p>
    <p><strong>{% trans 'Year' %}:</strong> {{ zotero_entry.data.date }}</p>
  </div>
    
    <!-- Display the error or the fetched Zotero entry -->
  {% if 'error' in zotero_entry %}
    <p><strong>{% trans 'Error' %}:</strong> {{ zotero_entry.error }}</p>
  {% endif %}

  <!-- Add additional details or actions as needed -->

  <a class="font-bold hover:text-main-graded-900" href="{% url 'corpus:bibliography' %}">{% trans 'Back to Bibliography' %}</a>
</div>
{% endblock %} 

treeflow/corpus/templates/comment_data.html
{% for comment in comments %}
    {{ comment.comment }}
    {% if not forloop.last %} | {% endif %}
{% empty %}
– 
{% endfor %}

treeflow/corpus/templates/comment_form.html
<!-- comment_form.html -->
{% load static i18n %}

<div class="fixed inset-0 flex items-center justify-center w-full h-full overflow-y-auto bg-gray-600 bg-opacity-50">
  <div class="p-4 overflow-hidden text-left transition-all transform bg-white rounded-lg shadow-xl sm:max-w-lg sm:w-full">
    <!-- Modal content here -->
    <form id="comment-form" method="post" hx-post="{% url 'corpus:comment_form' related_model_id %}?related_model_type={{ related_model_type }}" hx-trigger="submit" hx-swap="none">
      {% csrf_token %}
      {{ formset.management_form }}
      {% for form in formset %}
        <div class="grid grid-cols-2 gap-4 mb-4">
          {{ form.id }}
          {{ form.comment.label_tag }} {{ form.comment }}
          {{ form.DELETE.label_tag }} {{ form.DELETE }}

          <!-- Render 'uncertain', 'to_discuss', and 'new_suggestion' fields if 'Token' is the related model -->
          {% if form.fields.uncertain %}
            <div>{{ form.uncertain.label_tag }} {{ form.uncertain }}</div>
          {% endif %}
          {% if form.fields.to_discuss %}
            <div>{{ form.to_discuss.label_tag }} {{ form.to_discuss }}</div>
          {% endif %}
          {% if form.fields.new_suggestion %}
            <div>{{ form.new_suggestion.label_tag }} {{ form.new_suggestion }}</div>
          {% endif %}
          <!-- Render the is_new hidden field -->
          {{ form.is_new.as_hidden }}
        </div>
      {% endfor %}
      <div class="flex flex-row gap-2">
        <button type="submit" class="px-4 py-2 font-bold text-white rounded bg-main hover:bg-main-dark">{% trans 'Submit' %}</button>
        <button type="button" class="px-4 py-2 font-bold text-white rounded bg-error-graded-600 hover:bg-error-graded-800" onclick="closeCommentModal()">{% trans 'Close' %}</button>
        <button onclick="toggleTransparency()" class="flex flex-row px-4 py-2 text-base font-medium text-white rounded bg-off hover:bg-off-dark">
          <svg class="w-6 h-6 text-white" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" /> <path d="M16 8v-4h-12v12.01h4" stroke-dasharray=".001 4" /> <rect x="8" y="8" width="12" height="12" rx="2" />
          </svg>
          <span>{% trans 'Toggle Transparency' %}</span>
        </button>
      </div>
    </form>
  </div>
</div>

treeflow/corpus/templates/gloss_data.html
{{ token.gloss }}

treeflow/corpus/templates/line_update.html
<!-- line_update.html -->
<div id="line-content-{{ token_id }}"  hx-swap-oob="true">
    {{ line_data|safe }}
</div>

treeflow/corpus/templates/pos_feature_form.html
{% load static i18n %}

<!-- pos_feature_form.html -->
<div class="container mx-auto overflow-auto">
  <div class="inline-block w-full p-4 overflow-hidden text-left align-bottom transition-all transform bg-white rounded-lg shadow-xl" role="dialog" aria-modal="true" aria-labelledby="modal-headline">
    <form id="pos-feature-form" method="post" hx-post="{% url 'corpus:pos_feature_form' token_id=token.id %}" hx-trigger="submit" hx-swap="none" class="flex flex-row w-full p-4">
      {% csrf_token %}
      <div class="w-full">
        <label class="block mb-2 text-sm font-bold text-gray-700" for="pos">Part of Speech:</label>
        <div class="grid grid-cols-2">
          <div class="p-2 bg-gray-100">
            {{ pos_formset.management_form }}
            {% for form in pos_formset %}
              <div class="grid grid-cols-2 gap-4 mb-4">
                {{ form.id }}
                {{ form.pos.label_tag }} {{ form.pos }}
                {{ form.DELETE.label_tag }} {{ form.DELETE }} <!-- Render the delete checkbox -->
              </div>
            {% endfor %}
          </div>
          <div id="features-container" class="contents">
            {{ feature_formset.management_form }}
            {% for form in feature_formset %}
              <div class="grid grid-cols-2 gap-4 p-2 mb-4">
                {{ form.id }}
                {{ form.feature.label_tag }} {{ form.feature }}
                {{ form.feature_value.label_tag }} {{ form.feature_value }}
                {{ form.DELETE.label_tag }} {{ form.DELETE }} <!-- Render the delete checkbox -->
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </form>
    <div class="flex flex-row items-center gap-2">
      <button type="submit" class="px-4 py-2 text-base font-medium text-white rounded-md bg-main hover:bg-main-dark">{% trans 'Save' %}</button>
      <button type="button" class="px-4 py-2 text-base font-medium text-white rounded-md bg-error-graded-600 hover:bg-error-graded-800" onclick="closeFeatureModal()">{% trans 'Cancel' %}</button>
      <button onclick="toggleTransparency()" class="flex flex-row px-4 py-2 text-base font-medium text-white rounded bg-off hover:bg-off-dark">
        <svg class="w-6 h-6 text-white" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" /> <path d="M16 8v-4h-12v12.01h4" stroke-dasharray=".001 4" /> <rect x="8" y="8" width="12" height="12" rx="2" />
        </svg>
        <span>{% trans 'Toggle Transparency' %}</span>
      </button>
    </div>
  </div>
</div>

treeflow/corpus/templates/pos_feature_update.html
<!-- pos_feature_update.html -->
<div id="pos-content-{{ token_id }}" hx-swap-oob="true">
    {{ pos_data|safe }}
</div>
<div id="features-content-{{ token_id }}" hx-swap-oob="true">
    {{ features_data|safe }}
</div>

treeflow/corpus/templates/section_update.html
<div id="sentence-senses-{{ section_id }}" hx-swap-oob="true">
    {{ section_sense_data|safe }}
</div>

treeflow/corpus/templates/sense_data.html
{% for sense in token.senses.all %}
{{ sense.sense }}
{% if not forloop.last %}, {% endif %}
{% empty %}
_
{% endfor %}

treeflow/corpus/templates/source_create.html
{% extends 'base.html' %}
{% load i18n%}

{% block content %}
        <form class="flex flex-col items-center justify-center h-screen" method="post" action="">
            {% csrf_token %}
            {{ form.as_table }}
            {{ form.bibentry_forms.management_form }}
            {% for bibentry_form in form.bibentry_forms %}
                {{ bibentry_form.as_modal }}
            {% endfor %}
            <input type="submit" value={% trans 'Submit' %} class="px-4 py-2 font-bold text-white rounded bg-main hover:bg-main-dark">
        </form>
{% endblock %}

treeflow/corpus/templates/source_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans 'Sources' %}</h1>
    {% for source in object_list %}
        <li>{{source.id}} - {{ source.type }}</li>
    {% empty %}
        <li>{% trans 'No sources yet.' %}</li>
    {% endfor %}
    </ul>
{% endblock %}

treeflow/corpus/templates/update_token.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

<div class="container px-4 py-2 mx-auto">
  <h1 class="mb-6 text-2xl font-semibold">{% trans 'Edit Token' %}</h1>

  {% if form.errors %}
  <div class="px-4 py-2 font-bold text-white bg-red-500 rounded-t">
    {% trans 'There was a problem with your submission.' %}
  </div>
  <div class="px-4 py-3 text-red-700 bg-red-100 border border-t-0 border-red-400 rounded-b">
    <ul>
      {% for field in form %}
      {% for error in field.errors %}
      <li><strong>{{ field.label }}:</strong> {{ error }}</li>
      {% endfor %}
      {% endfor %}
    </ul>
  </div>
  {% endif %}

  <form method="post" action="{% url 'corpus:update_token' %}" class="w-full max-w-lg">
    {% csrf_token %}

    {% for field in form %}
    <div class="mb-4">
      <label for="{{ field.id_for_label }}" class="block mb-2 text-sm font-bold text-gray-700">
        {{ field.label }}
      </label>
      <!-- Here you need to manually construct the form field element -->
      <input type="text" name="{{ field.name }}" id="{{ field.id_for_label }}"
        value="{{ field.value|default_if_none:"" }}"
        class="w-full px-3 py-2 leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline" />
      {% if field.help_text %}
      <p class="text-xs italic text-gray-600">{{ field.help_text }}</p>
      {% endif %}DoesNotExist
      {% endif %}
    </div>
    {% endfor %}


    {% if token_id %}
    <input type="hidden" name="token_id" value="{{ token_id }}">
    {% endif %}

    <button type="submit"
      class="px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700 focus:outline-none focus:shadow-outline">
      {% trans 'Save changes' %}
    </button>
  </form>

  <a href="{% url 'corpus:tokens' %}" class="inline-block mt-4 text-blue-700 hover:underline">{% trans 'Back to token list' %}</a>
</div>

{% endblock content %}