config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.i18n import set_language
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from treeflow.views.publications import zotero_view
from strawberry.django.views import AsyncGraphQLView, GraphQLView



urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path("contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"),
    path("publications/",zotero_view, name="publications"),
    path("methodology/", TemplateView.as_view(template_name="pages/methodology.html"), name="methodology"),
    path("resources/", TemplateView.as_view(template_name="pages/resources.html"), name="resources"),
    path("team/", TemplateView.as_view(template_name="pages/team.html"), name="team"),
    path('kosh/', TemplateView.as_view(template_name="index.html"), name="kosh"),
    path('corpus/', include('treeflow.corpus.urls', namespace='corpus')),
    path('dict/', include('treeflow.dict.urls', namespace='dict')),
    path('images/',include('treeflow.images.urls', namespace='images')),
    path("search/", include("treeflow.search.urls", namespace="search")),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("treeflow.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("select2/", include("django_select2.urls")),
    # i18n
    path('i18n/setlang/', set_language, name='set_language'),
    #rest
    path('api/', include('treeflow.rest.urls', namespace='api')),
    # drf-spectacular views
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),




    # Your stuff: custom urls includes go here

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
        #django browser reload
        path("__reload__/", include("django_browser_reload.urls")),

    ]

    if "django_browser_reload" in settings.INSTALLED_APPS:
        urlpatterns = [path("__reload__/", include("django_browser_reload.urls"))] + urlpatterns

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

treeflow/dict/urls.py
from django.urls import include, path
from treeflow.dict.views.save_sense import save_sense
from treeflow.dict.views.save_lemma import save_lemma
from django.views.generic import TemplateView
from treeflow.dict.views.lemma_details import lemma_details

from treeflow.dict.views.lemmas_list import lemmas_list
from treeflow.dict.views.lemma_edit import lemma_edit
from treeflow.dict.views.update_lemma import update_lemma
from treeflow.dict.views.filter_lemmas import filter_lemmas
from treeflow.dict.views.fetch_alphabet import fetch_alphabet
from treeflow.dict.views.dictionary_entry import lemma_details as edit_lemma_details

app_name = "treeflow.dict"
urlpatterns = [
        path("save_sense/", save_sense, name="save_sense"),
        path("save_lemma/", save_lemma, name="save_lemma"),
        path("", lemmas_list, name="dictionary"),
        path("<uuid:lemma_id>/", lemmas_list, name="lemmas"),
        path("fetch_Lemma/<uuid:lemma_id>/",lemma_details, name="lemma_details"),
        path("edit_Lemma/<uuid:lemma_id>/", lemma_edit, name="lemma_edit"),
        path("update_lemma/<uuid:lemma_id>/", update_lemma, name="update_lemma"),
        path("filter_lemmas/", filter_lemmas, name="filter_lemmas"),
        path("fetch_alphabet/", fetch_alphabet, name="fetch_alphabet"),
        path("fetch_attestations/<uuid:lemma_id>/", edit_lemma_details, name="fetch_attestations")
]

treeflow/dict/forms/lemma_form.py
# forms.py
from django import forms
from treeflow.dict.models import Lemma
from treeflow.dict.forms.widgets import LemmaWidget
from treeflow.dict.forms.widgets import SenseWidget


class LemmaForm(forms.ModelForm):
    class Meta:
        model = Lemma
        fields = ['word', 'language', 'multiword_expression', 'related_lemmas', 'related_senses']
        widgets = {
            'related_lemmas': LemmaWidget,
            'related_senses': SenseWidget(attrs={'id': 'lemma_related_senses'})}

treeflow/dict/forms/sense_form.py
from django import forms
from treeflow.dict.forms.widgets import SenseWidget
from treeflow.dict.models import Sense

class SenseForm(forms.ModelForm):
    class Meta:
        model = Sense
        widgets = {
            'related_senses': SenseWidget(attrs={'id': 'sense_related_senses'}),
        }
        fields = ['sense', 'language', 'lemma_related', 'related_senses']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['sense'].widget.attrs.update({
            'placeholder': 'Enter sense here...',
            'style': 'max-height: 200px; resize: vertical; width: 100%; border-radius: 5px;',
        })
        self.fields['language'].widget.attrs.update({
            'style': 'border-radius: 5px;',
        })

treeflow/dict/views/dictionary_entry.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from treeflow.dict.models.lemma import Lemma
from treeflow.dict.models.sense import Sense
from treeflow.corpus.models.token import Token
from treeflow.corpus.models.section import Section

import logging

logger = logging.getLogger(__name__)


def lemma_details(request, lemma_id):
    lemma = Lemma.objects.prefetch_related('related_senses','related_senses__token_senses__section_tokens','related_senses__token_senses__lemmas').get(id=lemma_id)
    # tokens = [token for token in  lemma.first().token_lemmas.all()]
    # related_senses = [sense for sense in lemma.first().related_senses.all()]
    # lemma = lemma.first()
    context = {
        'lemma': lemma
    }
    
    return render(request, 'dictionary_entry.html', context)

treeflow/dict/views/fetch_alphabet.py
from django.core.cache import cache
from django.http import JsonResponse

from treeflow.corpus.templatetags.dict_tags import getCustomAlphabeticalOrder
from treeflow.dict.models.lemma import Lemma

# import time


def fetch_alphabet(request):
    usesCache = False
    lemmas = cache.get('lemmas')
 
    if lemmas is None:
       print(f"({__name__}) Cache not available: Querying lemmas from database")
       lemmas = Lemma.objects.values('word')
    else:
        usesCache = True

    processed_data = set()

    # start_time = time.time()

    for item in lemmas:
        if not usesCache:
            if (s := item['word']) != "":
                processed_data.add(s[0])
        else:
            if (s := item.word) != "":
                processed_data.add(s[0])

    # end_time = time.time()
    # elapsed_time = end_time - start_time
    # print(f"The loop took {elapsed_time} seconds.")

    return JsonResponse({'alphabet': sort(processed_data)})

def sort(data):
    c_order = getCustomAlphabeticalOrder()
    return sorted([x for x in data if x != ""], key=lambda x: c_order.index(x) if x in c_order else len(c_order))




treeflow/dict/views/filter_lemmas.py
import logging
import re

from django.core.cache import cache
from django.db.models import Q
from django.http import HttpResponse
from django.urls import reverse

from treeflow.corpus.templatetags.dict_tags import customABCSort
from treeflow.dict.models.lemma import Lemma

logger = logging.getLogger(__name__)

def filter_lemmas(request):
    filter_word = request.GET.get('filter_word', '')
    search_mode = request.GET.get('search_mode', '')

    # Filter modes
    filter_modes = {
        'icontains': '__icontains',
        'iexact': '__iexact',
        'startswith': '__startswith',
        'endswith': '__endswith',
        'regex': '__regex',
        'relatives': 'relatives',
    }

    filter_mode = '__startswith' 

    if search_mode in filter_modes:
        filter_mode = filter_modes[search_mode]

    # Filter kwargs
    filter_kwargs = {}
    if filter_word:
        if search_mode == 'regex':
            logger.info(f"Regex search: {filter_word}")
            try:
                pattern = re.compile(filter_word)
                logger.info(f"Regex pattern: {pattern}")
                filter_kwargs[f'word{filter_mode}'] = pattern
            except re.error as e:
                logger.error(f"Regex compilation error: {e}")
                return HttpResponse(status=400)  
            
        if search_mode != 'relatives':
            filter_field = f'word{filter_mode}'
            filter_kwargs[filter_field] = filter_word

    # Filter query
    cached_query = cache.get('lemmas')
    if cached_query is None:
        cached_query = Lemma.objects.all()
    
    initial_lemma = None

    if cached_query is not None and cached_query.exists():
        if search_mode == 'relatives' and filter_word:
            initial_lemma = cached_query.filter(word__iexact=filter_word).first()
            if hasattr(initial_lemma, 'related_lemmas'):
                related_lemmas = initial_lemma.related_lemmas.all()
                filtered_lemmas = related_lemmas
            else:
                filtered_lemmas = []
        elif filter_kwargs:
            filtered_lemmas = cached_query.filter(Q(**filter_kwargs))
        else:
            filtered_lemmas = cached_query.all()

    # Div generation
    lemma_divs = []

    filtered_lemmas = customABCSort(filtered_lemmas)
    if search_mode == 'relatives' and initial_lemma is not None:
        filtered_lemmas.insert(0, model_to_dict(initial_lemma))

    for lemma in filtered_lemmas:
        url = reverse('dict:lemma_details', kwargs={'lemma_id': lemma['id']})

        div_html = (
            f'<div id="{lemma["id"]}" '
            f'hx-get="{url}" '
            f'hx-target="#lemma-details" '
            f'hx-replace-url="/dict/{lemma["id"]}/" '
            f'onclick="selection(this)" '
            f'class="p-1 m-1 mb-0 text-center rounded-sm shadow-sm cursor-pointer '
            f'hover:text-white hover:bg-main shadow-black scroll-m-1">'
            f'{lemma["word"]}'
            f'</div>'
        )
        lemma_divs.append(div_html)

    lemma_html = '\n'.join(lemma_divs)

    return HttpResponse(lemma_html)

def model_to_dict(instance):
    opts = instance._meta
    data = {}
    for field in opts.fields:
        data[field.name] = getattr(instance, field.name)
    return data

treeflow/dict/views/lemma_details.py
from django.shortcuts import render, get_object_or_404
from treeflow.dict.models.lemma import Lemma


def lemma_details(request, lemma_id):
    lemma = get_object_or_404(Lemma, id=lemma_id)
    related_lemmas = lemma.related_lemmas.all()
    related_senses = lemma.related_senses.all()

    context = {
        'id': lemma.id,
        'word': lemma.word,
        'language': lemma.language,
        'categories': lemma.categories,
        'multiword_expression': lemma.multiword_expression,
        'related_lemmas': related_lemmas,
        'related_senses': related_senses,
    }
    
    return render(request, 'lemma_details.html', context)

treeflow/dict/views/lemma_edit.py
import logging
from django.shortcuts import render, redirect, get_object_or_404
from treeflow.dict.forms.sense_form import SenseForm
from treeflow.dict.forms.lemma_form import LemmaForm
from treeflow.dict.models.lemma import Lemma

def lemma_edit(request, lemma_id):
    lemma_instance = None
    if lemma_id:
        lemma_instance = get_object_or_404(Lemma, id=lemma_id)

    lemma_form = LemmaForm(instance=lemma_instance)
    sense_form = SenseForm()

    context = {
        'lemma_form': lemma_form, 
        'sense_form': sense_form,
    }
    return render(request, 'lemma_form.html', context)

treeflow/dict/views/lemmas_list.py
from django.core.cache import cache
from django.shortcuts import render

from treeflow.dict.models.lemma import Lemma

def lemmas_list(request, lemma_id = None):
    usesCache = False
    lemmas = cache.get('lemmas')

    if lemmas is None:
        print(f"({__name__}) Cache not available: Querying lemmas from database")
        lemmas = Lemma.objects.values('id', 'word')
    else:
        usesCache = True
        
    context = {
        'lemmas': lemmas,
    }

    if lemma_id:
        context['lemma_id'] = lemma_id
        lemma = lemmas.filter(id=lemma_id).first()
        context['lemma_first_letter'] = lemma['word'][0].lower() if not usesCache else lemma.word[0].lower()
    return render(request, 'dictionary.html', context)

treeflow/dict/views/save_lemma.py
import logging
from django.http import HttpResponseBadRequest
from django.shortcuts import render
from treeflow.dict.forms.lemma_form import LemmaForm

# Configure logger
logger = logging.getLogger(__name__)

def save_lemma(request):
    if request.method == 'POST':
        form = LemmaForm(request.POST)

        if form.is_valid():
            lemma = form.save()
            logger.info(f"Lemma object with ID {lemma.id} was created successfully.")

            # If the request is via HTMX
            if 'HX-Request' in request.headers:
                logger.info("HTMX request for lemma creation.")
                new_form = LemmaForm()  # Return a new, empty form
                return render(request, 'lemma_plain_form.html', {'lemma_form': new_form})
            else:
                # Handle non-HTMX request if necessary
                logger.info("Non-HTMX request for lemma creation.")

        else:
            logger.error(f"Form errors: {form.errors}")
            if 'HX-Request' in request.headers:
                logger.info("HTMX request with form errors.")
                # Return the form with errors for HTMX requests
                return render(request, 'lemma_plain_form.html', {'lemma_form': form})
            else:
                # Handle non-HTMX request with form errors if necessary
                logger.info("Non-HTMX request with form errors.")

    else:
        logger.warning("Received non-POST request on save_lemma view.")
        return HttpResponseBadRequest()

    return HttpResponseBadRequest("Invalid request method.")

treeflow/dict/views/save_sense.py
import logging
from django.http import HttpResponseBadRequest
from django.shortcuts import render
from treeflow.dict.forms.sense_form import SenseForm

# Configure logger
logger = logging.getLogger(__name__)

def save_sense(request):
    if request.method == 'POST':
        form = SenseForm(request.POST)

        if form.is_valid():
            sense = form.save()
            logger.info(f"Sense object with ID {sense.id} was created successfully.")

            # If the request is via HTMX
            if 'HX-Request' in request.headers:
                logger.info("HTMX request for sense creation.")
                new_form = SenseForm()  # Return a new, empty form
                return render(request, 'sense_form.html', {'sense_form': new_form})
            else:
                # Handle non-HTMX request if necessary
                logger.info("Non-HTMX request for sense creation.")

        else:
            logger.error(f"Form errors: {form.errors}")
            if 'HX-Request' in request.headers:
                logger.info("HTMX request with form errors.")
                # Return the form with errors for HTMX requests
                return render(request, 'sense_form.html', {'sense_form': form})
            else:
                # Handle non-HTMX request with form errors if necessary
                logger.info("Non-HTMX request with form errors.")

    else:
        logger.warning("Received non-POST request on save_sense view.")
        return HttpResponseBadRequest()

    return HttpResponseBadRequest("Invalid request method.")

treeflow/rest/views/lemma.py
from rest_framework import viewsets
from rest_framework.pagination import PageNumberPagination
from treeflow.dict.models import Lemma
from treeflow.rest.serializers.lemma import LemmaSerializer
from drf_spectacular.utils import extend_schema

class LemmaPagination(PageNumberPagination):
    page_size = 10
    page_size_query_param = 'page_size'
    max_page_size = 1000

@extend_schema(tags=['lemmas'])
class LemmaViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Lemma.objects.prefetch_related('related_senses', 'related_lemmas').all()

    serializer_class = LemmaSerializer
    pagination_class = LemmaPagination 

treeflow/dict/templates/lemma_details.html
{% load i18n %}

<div>
  <h3 class="p-2 mb-4 text-4xl font-bold text-left bg-white rounded-md w-fit text-main-dark-graded-900">{{ word }}</h3>
  {% if user.is_authenticated %}
    <input type="button" hx-get="{% url 'dict:lemma_edit' id %}" hx-target="#lemmaModalContent" hx-trigger="click" class="px-1 py-2 mb-2 font-semibold text-white rounded-md shadow-sm cursor-pointer bg-off shadow-black hover:bg-main" onclick="openLemmaModal()" value="{% trans 'Edit Lemma' %}" />
    {% comment %} <input type="button" class="px-1 py-2 font-semibold text-white rounded-md bg-error hover:bg-action" value="Delete Lemma" /> {% endcomment %}
  {% else %}
    <div class="p-2 mb-2 underline rounded-md w-fit bg-slate-300">
      {% trans 'You must be logged in to edit this lemma.' %}
    </div>
  {% endif %}
  <div class="flex flex-col h-full gap-2">
    <div class="flex flex-row gap-2">
      {% if multiword_expression %}
        <div class="p-2 rounded-md bg-main-dark-graded-300 w-fit">
          <span class="font-bold text-white">{% trans 'Multiword Expression' %}</span>
        </div>
      {% endif %}
    </div>
    <hr class="w-full mt-5 border-black" />
    <div class="flex flex-row gap-2 mb-1 font-semibold">
      <span class="my-auto underline">{% trans 'Related lemmas' %}</span>
      {% if related_lemmas %}
        <button class="flex flex-row p-1 text-white rounded-md shadow-sm cursor-pointer bg-off shadow-black hover:bg-main" onclick="searchForRelatives('{{ word }}')">
          <svg class="w-6 h-6 text-white rotate-180" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" /> <circle cx="12" cy="18" r="2" /> <circle cx="7" cy="6" r="2" /> <circle cx="17" cy="6" r="2" /> <path d="M7 8v2a2 2 0 0 0 2 2h6a2 2 0 0 0 2 -2v-2" /> <line x1="12" y1="12" x2="12" y2="16" />
          </svg>
          <span>{% trans 'Search for relatives' %}</span>
        </button>
      {% endif %}
    </div>
    <div id="related-lemmas-div" class="grid hover:grid-rows-[1fr] transition-[grid-template-rows] duration-500 delay-200 gap-2">
      <div class="overflow-hidden">
        {% if related_lemmas %}
          <div class="flex flex-row flex-wrap w-full gap-2 p-2">
            {% for related_lemma in related_lemmas %}
              <div class="p-2 rounded-md bg-slate-300 w-fit hover:underline hover:cursor-pointer" onclick="changeLemma(this)">{{ related_lemma.word }}</div>
            {% endfor %}
          </div>
        {% else %}
          <div class="p-2">
            {% trans 'No related lemmas found.' %}
          </div>
        {% endif %}
      </div>
      <div id="toggle-related-div" class="justify-center hidden w-full bg-gray-400 cursor-pointer hover:bg-gray-600" onclick="toggleRelatedLemmas()">
        <svg class="w-8 h-8 rotate-180 text-off" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 15l7-7 7 7" />
        </svg>
      </div>
    </div>
    <hr class="w-full mt-5 border-black" />
    <div class="flex flex-row gap-2 mb-1 font-semibold">
      <span class="my-auto underline">{% trans 'Senses' %}</span>
      {% if related_senses and user.is_authenticated %}
        <button id="attestation-btn" class="flex flex-row p-1 text-white rounded-md shadow-sm cursor-pointer bg-off shadow-black hover:bg-main" hx-get="{% url 'dict:fetch_attestations' id %}" hx-target="#attestation-div" hx-trigger="click" onclick="toggleAttestations()">
          <svg class="w-6 h-6 text-white" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" /> <line x1="4" y1="20" x2="7" y2="20" /> <line x1="14" y1="20" x2="21" y2="20" /> <line x1="6.9" y1="15" x2="13.8" y2="15" /> <line x1="10.2" y1="6.3" x2="16" y2="20" /> <polyline points="5 20 11 4 13 4 20 20" />
          </svg>
          <span>{% trans 'View attestations' %}</span>
        </button>
      {% endif %}
    </div>
    <div id="attestation-div" class="overflow-hidden" onchange="console.log('test')">
      {% if related_senses %}
        <div class="flex flex-row flex-wrap gap-2 p-2">
          {% for related_sense in related_senses %}
            <div class="p-2 rounded-md bg-slate-300 w-fit">
              {{ related_sense.sense }}<sup>{{ related_sense.language }}</sup>
            </div>
          {% endfor %}
        </div>
      {% else %}
        <div>
          {% trans 'No related senses found.' %}
        </div>
      {% endif %}
    </div>
  </div>

  <div class="fixed inset-0 z-50 hidden w-full h-full overflow-y-auto bg-gray-600 bg-opacity-50" id="lemmaModal">
    <div class="flex items-center justify-center min-h-screen">
      <div class="p-4 mx-auto bg-white rounded-lg shadow-lg">
        <!-- Modal content here -->
        <div id="lemmaModalContent"></div>
      </div>
    </div>
  </div>
</div>

<script>
  function searchForRelatives(lemmaWord) {
    selectSpecificSearchMode('relatives')
  
    document.getElementById('search-input').value = lemmaWord
    document.getElementById('search-button').disabled = false
    document.getElementById('clear-search-button').disabled = false
  
    search(lemmaWord)
  }
  
  function changeLemma(e) {
    const lemmaList = document.querySelector('#lemma-list')
  
    if (lemmaList) {
      lemmaList.childNodes.forEach((child) => {
        if (child.nodeType === Node.ELEMENT_NODE && child.innerText === e.innerText) {
          child.click()
        }
      })
    }
  }
  
  function openLemmaModal() {
    document.getElementById('lemmaModal').classList.remove('hidden')
  }
  
  function closeLemmaModal() {
    document.getElementById('lemmaModal').classList.add('hidden')
  }
  
  function toggleRelatedLemmas() {
    const relatedLemmasDiv = document.getElementById('related-lemmas-div')
  
    if (relatedLemmasDiv.classList.contains('grid-rows-[0fr]')) {
      relatedLemmasDiv.classList.remove('grid-rows-[0fr]')
      relatedLemmasDiv.classList.add('grid-rows-[1fr]')
    }
    //else {
    //  relatedLemmasDiv.classList.remove('grid-rows-[1fr]')
    //  relatedLemmasDiv.classList.add('grid-rows-[0fr]')
    //}
  }
  
  function toggleAttestations() {
    startLoading('Fetching attestations...')
  }
  
  document.addEventListener('htmx:afterRequest', () => {
    const relatedLemmasDiv = document.getElementById('related-lemmas-div')
    relatedLemmasDiv.classList.add('grid-rows-[0fr]')
  
    const relatedLemmasToggle = document.getElementById('toggle-related-div')
    relatedLemmasToggle.classList.remove('hidden')
    relatedLemmasToggle.classList.add('flex')
  
    document.getElementById('attestation-btn').classList.add('hidden')
  
    stopLoading()
  })
</script>

treeflow/dict/templates/lemma_form.html
{% load i18n %}

<div class="container mx-auto">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
  
  <div class="flex flex-row w-full gap-2">
    <div class="w-1/2 px-3 mb-6">
      <div class="p-6 bg-white rounded-lg shadow-md">
        {{ lemma_form.media.css }}
        <h2 class="mb-4 text-lg font-semibold text-p-gray-graded-900">Lemma Form</h2>
        <form id="lemma-form" method="post" hx-post="{% url 'dict:update_lemma' lemma_form.instance.id %}" hx-target="#lemma-form" hx-swap="outerHTML">
          {% csrf_token %}
          {% for field in lemma_form %}
            <div class="mb-4">
              <label for="{{ field.id_for_label }}" class="block text-sm font-medium text-p-gray">{{ field.label }}</label>
              {{ field }}
              {% if field.help_text %}
                <p class="mt-2 text-sm text-gray-600">{{ field.help_text }}</p>
              {% endif %}
              {% for error in field.errors %}
                <p class="text-sm text-error">{{ error }}</p>
              {% endfor %}
            </div>
          {% endfor %}
          <button type="submit" name="submit_lemma" class="flex justify-center w-full px-4 py-2 text-sm font-medium text-white border border-transparent rounded-md shadow-sm bg-off hover:bg-off-dark focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-off-dark">{% trans 'Update Lemma' %}</button>
        </form>
        {{ lemma_form.media.js }}
      </div>
    </div>
    <div class="w-1/2 px-3 mb-6">
      <div class="p-6 bg-white rounded-lg shadow-md">
        {{ sense_form.media.css }}
        <h2 class="mb-4 text-lg font-semibold text-gray-800">Sense Form</h2>
        <form id="sense-form" method="post" hx-post="{% url 'dict:save_sense' %}" hx-target="#sense-form" hx-swap="outerHTML">
          {% csrf_token %}
          {% for field in sense_form %}
            <div class="mb-4">
              <label for="{{ field.id_for_label }}" class="block text-sm font-medium text-gray-700">{{ field.label }}</label>
              {{ field }}
              {% if field.help_text %}
                <p class="mt-2 text-sm text-gray-600">{{ field.help_text }}</p>
              {% endif %}
              {% for error in field.errors %}
                <p class="text-sm text-error">{{ error }}</p>
              {% endfor %}
            </div>
          {% endfor %}
          <button type="submit" name="submit_sense" id="submit_sense" disabled class="flex justify-center w-full px-4 py-2 text-sm font-medium text-white border border-transparent rounded-md shadow-sm disabled:bg-gray-500 bg-off hover:bg-off-dark focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-off-dark">{% trans 'Add Sense' %}</button>
        </form>
        {{ sense_form.media.js }}
      </div>
    </div>
  </div>
  <div class="flex justify-end">
    <button onclick="closeLemmaModal()" class="px-4 py-2 mt-4 font-bold text-white rounded bg-error-graded-600 hover:bg-error-graded-800">{% trans 'Close' %}</button>
  </div>
  <script defer>
    document.getElementById('id_sense').addEventListener('input', function (e) {
      if (e.target.value.trim().length > 0) {
        document.getElementById('submit_sense').disabled = false
        return
      }
      document.getElementById('submit_sense').disabled = true
    })
  </script>
</div>